_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "output/sparsercnn_evc_sc/model_0149999.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("CrowdHuman_train",)
  TEST:  ("CrowdHuman_val",)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.000025
  STEPS: (1000,) # 15000 / 4 = 3750 iter = 1 epoch
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 10000 # 4 epoch
TEST:
  EVAL_PERIOD: 10000 # 4 epoch
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output/default_crowdhuman_our"
