_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "weights/R-50.pkl" #"output/sparsercnn_evc/model_0129999.pth" 
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("CrowdHuman_train",)
  TEST:  ("CrowdHuman_val",)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.00005
  STEPS: (100000,) # 15000 / 4 = 3750 iter = 1 epoch
  MAX_ITER: 170000
  CHECKPOINT_PERIOD: 10000 # 4 epoch
TEST:
  EVAL_PERIOD: 10000 #5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output/default_crowdhuman_baseline"
