_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "weights/CoTNet50-350epoch.pth"
  BACKBONE:
    NAME: "build_cotnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("cityperson_train",)
  TEST:  ("cityperson_val",)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.000005
  STEPS: (13387,)  # 27epoch    
  MAX_ITER: 17850 # 36epoch  2975*36=107100   steps = 107100/6 = 17850
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1500
  # MIN_SIZE_TRAIN: (1024,)
  # MAX_SIZE_TRAIN: 2048
  # MIN_SIZE_TEST: 1024
  # MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output/cityperson_output_test"
